<a href="https://colab.research.google.com/github/paradox-86678/DATA_HANDLING_VISUALIZATION.GITHUB/blob/main/Labsheet2_Flickr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from functools import reduce

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Datasets/BL-Flickr-Images-Book.csv")

In [ ]:
for col in df.columns:
  print(col)

Identifier
Edition Statement
Place of Publication
Date of Publication
Publisher
Title
Author
Contributors
Corporate Author
Corporate Contributors
Former owner
Engraver
Issuance type
Flickr URL
Shelfmarks

In [ ]:
to_drop=['Shelfmarks','Edition Statement','Contributors','Corporate Contributors','Engraver','Flickr URL']

In [ ]:
df.drop(to_drop,inplace=True,axis=1)
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Corporate Author,Former owner,Issuance type
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,NaN,NaN,monographic
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",NaN,NaN,monographic
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",NaN,NaN,monographic
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",NaN,NaN,monographic
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",NaN,NaN,monographic

In [ ]:
df.set_index('Identifier',inplace=True)
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Corporate Author,Former owner,Issuance type
Identifier,,,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,NaN,NaN,monographic
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",NaN,NaN,monographic
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",NaN,NaN,monographic
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",NaN,NaN,monographic
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",NaN,NaN,monographic

In [ ]:
unwanted_characters=['[',',','-']
def clean_date(item):
  dop=str(item.loc['Date of Publication'])
  if dop=='nan' or dop[0]=='[':
    return np.NaN
  for character in unwanted_characters:
    if character in dop:
      character_index=dop.find(character)
      dop=dop[:character_index]
  return dop

In [ ]:
df['Date of Publication']=df.apply(clean_date,axis=1)

In [ ]:
df.head(15)

,Place of Publication,Date of Publication,Publisher,Title,Author,Corporate Author,Former owner,Issuance type
Identifier,,,,,,,,
206,London,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,NaN,NaN,monographic
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",NaN,NaN,monographic
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",NaN,NaN,monographic
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",NaN,NaN,monographic
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",NaN,NaN,monographic
481,London,1875,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",NaN,NaN,monographic
519,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",NaN,NaN,monographic
667,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",NaN,NaN,monographic
874,London],1676,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,NaN,NaN,monographic
1143,London,1679,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",NaN,NaN,monographic
1280,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,NaN,NaN,monographic
1808,Christiania,1859,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",NaN,NaN,monographic
1905,Firenze,1888,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",NaN,NaN,monographic
1929,Amsterdam,1839,NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,NaN,NaN,monographic
2836,Savona,1897,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",NaN,NaN,monographic

In [ ]:
#clean title
def clean_title(title):
  if title=='nan':
    return 'NaN'
  if title[0]=='[':
    title=title[1:title.find(']')]
  if 'by' in title:
    title=title[:title.find('by')]
  elif 'By' in title:
    title=title[:title.find('By')]
  if '[' in title:
    title=title[:title.find('[')]
  title=title[:-2]
  return title
# df['Title']=df['Title'].apply(clean_title)
# print(df.head())

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Datasets/BL-Flickr-Images-Book.csv")

In [ ]:
print(df['Title'])

0                       Walter Forbes. [A novel.] By A. A
1       All for Greed. [A novel. The dedication signed...
2       Love the Avenger. By the author of “All for Gr...
3       Welsh Sketches, chiefly ecclesiastical, to the...
4       [The World in which I live, and my place in it...
                              ...
8282    The Parochial History of Cornwall, founded on,...
8283    The History and Gazetteer of the County of Der...
8284    Magna Britannia; being a concise topographical...
8285    An historical, topographical and descriptive v...
8286    Collectanea Topographica et Genealogica. [Firs...
Name: Title, Length: 8287, dtype: object

In [ ]:
df['Title']=df['Title'].apply(clean_title)
print(df['Title'])

0                                           Walter Forbes
1                                           All for Greed
2                                        Love the Avenger
3       Welsh Sketches, chiefly ecclesiastical, to the...
4           The World in which I live, and my place in it
                              ...
8282        The Parochial History of Cornwall, founded on
8283         The History and Gazetteer of the County of D
8284    Magna Britannia; being a concise topographical...
8285    An historical, topographical and descriptive v...
8286              Collectanea Topographica et Genealogica
Name: Title, Length: 8287, dtype: object

In [ ]:
df.loc[391]

Identifier                                                           158296
Edition Statement                                                       NaN
Place of Publication                                                Québec
Date of Publication                                                    1887
Publisher                                                               NaN
Title                     Voyage au Canada ... fait depuis l'an 1751 à ...
Author                                                            B., J. C.
Contributors                      BONNEFONS, J. C.|CASGRAIN, Henri Raymond.
Corporate Author                                                        NaN
Corporate Contributors                                                  NaN
Former owner                                                            NaN
Engraver                                                                NaN
Issuance type                                                   monographic
Flickr URL                http://www.flickr.com/photos/britishlibrary/ta...
Shelfmarks                                British Library HMNTS 10470.f.18.
Name: 391, dtype: object